
const POLARIS_ICONS = {
  add: "add",
  alert: "alert",
  arrowDown: "arrowDown",
  arrowLeft: "arrowLeft",
  arrowRight: "arrowRight",
  arrowUp: "arrowUp",
  arrowUpDown: "arrowUpDown",
  calendar: "calendar",
  cancel: "cancel",
  cancelSmall: "cancelSmall",
  caretDown: "caretDown",
  caretUp: "caretUp",
  checkmark: "checkmark",
  chevronDown: "chevronDown",
  chevronLeft: "chevronLeft",
  chevronRight: "chevronRight",
  chevronUp: "chevronUp",
  circleCancel: "circleCancel",
  circleChevronDown: "circleChevronDown",
  circleChevronLeft: "circleChevronLeft",
  circleChevronRight: "circleChevronRight",
  circleChevronUp: "circleChevronUp",
  circleInformation: "circleInformation",
  circlePlus: "circlePlus",
  conversation: "conversation",
  delete: "delete",
  disable: "disable",
  dispute: "dispute",
  duplicate: "duplicate",
  embed: "embed",
  export: "export",
  external: "external",
  help: "help",
  horizontalDots: "horizontalDots",
  import: "import",
  notes: "notes",
  notification: "notification",
  print: "print",
  refresh: "refresh",
  risk: "risk",
  save: "save",
  search: "search",
  subtract: "subtract",
  view: "view",
};

export type polarisIconTypes = keyof typeof POLARIS_ICONS;